/**
 * strings.js — 所有用户可见文字集中在此文件
 * 翻译者只需修改本文件的值，不需要改其他代码。
 * 兼容浏览器（window.S）和 Node.js（module.exports）双上下文。
 */
const S = {

  /* ── 全局 / 导航 ── */
  app_title:           'Audio2Text',
  btn_add_title:       '添加文件',
  btn_settings_title:  '设置',
  sidebar_title:       '任务列表',
  filter_running:      '处理中',
  filter_queued:       '队列中',
  filter_done:         '已完成',
  btn_clear_finished:  '🗑 清空记录',
  btn_refresh:         '↻ 刷新',
  btn_refresh_title:   '刷新列表',

  /* ── 空状态 ── */
  empty_text:          '当前没有任务',
  empty_sub:           '把音频文件拖进来，或点击「＋ 添加」',
  drop_hint:           '松开以添加音频文件',

  /* ── 确认转写弹窗 ── */
  confirm_title:       '确认转写',
  confirm_file_count:  (n) => `（${n} 个文件）`,
  confirm_files_label: (n) => `待转写文件（${n} 个）`,
  confirm_files_sub:   '🎵 点亮 = 有背景音乐需分离 · 📂 改输出目录',
  confirm_unified:     '统一设置（可选，覆盖上方所有行）',
  confirm_music_label: '背景音乐：',
  confirm_outdir_label:'输出目录：',
  confirm_outdir_ph:   '点此选择统一目录（可选）',
  confirm_music_all:   '点击切换：全部有/无背景音乐',
  confirm_music_all_on:'全部有',
  confirm_music_all_off:'全部无',
  confirm_fmt_label:   '统一导出格式（可选）',
  confirm_fmt_sub:     '设置后覆盖每行的单独选择',
  fmt_no_unify:        '不统一（各自选择）',
  fmt_md_all:          '全部 Markdown (.md)',
  fmt_txt_all:         '全部 纯文本 (.txt)',
  fmt_srt_all:         '全部 SRT 字幕（视频剪辑/字幕制作）',
  fmt_vtt_all:         '全部 VTT 字幕（YouTube/网页）',
  btn_cancel:          '取消',
  btn_confirm_start:   '确定开始',

  /* ── 设置弹窗 ── */
  settings_title:      '设置',
  settings_env_label:  '运行环境',
  btn_env_refresh:     '↺ 重新检测',
  env_installing:      '正在安装…',
  settings_whisper:    'Whisper 模型（音频转文字）',
  btn_dl:              '⬇ 下载',
  settings_demucs:     'Demucs 模型（音乐/人声分离）',
  model_hint:          '符号说明：左侧 ‖ = 当前使用中 · 下拉中 ● = 已下载 · 下拉中无标记 = 未下载（转写时自动下载）',
  model_dl_hint:       '⬆ 下载位置可在下方目录设置中修改',
  settings_outdir:     '默认输出目录',
  btn_browse:          '浏览',
  settings_whisper_dir:'Whisper 模型目录',
  settings_demucs_dir: 'Demucs 模型目录',
  demucs_dir_hint:     '用于"有背景音乐"时的人声分离模型。首次使用需联网下载（约数百 MB）。',
  settings_python:     'Python 解释器',
  python_hint:         'Python 解释器本身无 CPU/GPU 版之分；GPU 加速取决于安装了哪个版本的 PyTorch（由上方"运行环境"区块的安装按钮自动处理）。',
  settings_ffmpeg:     'ffmpeg 目录（可选）',
  ffmpeg_ph:           '留空则使用系统 PATH 中的 ffmpeg',
  ffmpeg_hint:         'ffmpeg 用于读取音频时长（预计耗时功能）。转写本身不依赖它，不设置也能正常转写。',
  settings_fmt:        '默认输出格式',
  fmt_hint:            '每次添加文件时的默认选项，可在确认弹窗里单独修改。',
  fmt_md:              'Markdown (.md)',
  fmt_txt:             '纯文本 (.txt)',
  fmt_srt:             'SRT 字幕（视频剪辑/字幕制作）',
  fmt_vtt:             'VTT 字幕（YouTube/网页）',
  settings_theme:      '主题',
  theme_dark:          '深色',
  theme_light:         '浅色',
  settings_accent:     '强调色',
  btn_reset_accent:    '恢复默认',
  btn_settings_close:  '关闭',
  settings_lang:       '界面语言',
  btn_export_template: '⬇ 导出双语翻译模板',
  lang_drop_hint:      '拖入 .json 翻译文件',
  lang_hint:           '将翻译好的 .json 文件拖入右侧方框导入；点左上按钮下载双语模板作为参考。',
  lang_default:        '中文（默认）',
  lang_imported:       '✓ 已导入：{name}',
  lang_import_fail:    '导入失败，请检查文件格式',
  env_complete_label:  '环境已就绪',
  env_complete_hint:   '点"↺ 重新检测"可手动刷新',
  btn_settings_save:   '保存',
  python_ph:           '留空将自动检测',

  /* ── 环境检测行 ── */
  env_detecting:       '检测中…',
  env_detect_fail:     '检测失败',
  env_python_name:     'Python',
  env_python_note_ok:  '',
  env_python_note_miss:'请安装 Python 3.9+',
  env_fw_name:         'faster-whisper',
  env_fw_note:         '语音转文字核心库',
  env_torch_name:      'PyTorch',
  env_torch_note:      'demucs 人声分离所需的深度学习框架',
  env_demucs_name:     'demucs',
  env_demucs_note:     '人声/背景音乐分离库（"有背景音乐"功能专用，可选）',
  env_gpu_name:        'NVIDIA 显卡',
  env_gpu_note:        '有显卡则 PyTorch 可用 GPU 加速，无则使用 CPU',
  env_ok:              '✓ 已安装',
  env_miss:            '✗ 未安装',
  env_not_found:       '✗ 未找到',
  env_torch_cuda:      '✓ 已安装（GPU/CUDA 版）',
  env_torch_cpu:       '✓ 已安装（CPU 版）',
  env_gpu_ok:          (name) => `✓ ${name}`,
  env_gpu_miss:        '✗ 未检测到',
  env_torch_upgrade:   '检测到已装 CPU 版，可重装 GPU 版提速',
  btn_torch_upgrade:   '↑ 升级 GPU 版',
  env_torch_variant_title: 'GPU版需要NVIDIA显卡，速度快5-10倍；CPU版通用',
  env_torch_gpu_opt:   'GPU 版（推荐）',
  env_torch_cpu_opt:   'CPU 版（通用）',
  btn_install:         '⬇ 安装',
  env_gpu_hint:        (name) => `检测到 ${name}，推荐 GPU 版`,
  env_no_gpu_note:     '未检测到 NVIDIA 显卡，只可安装 CPU 版',
  env_torch_gpu_note:  (name) => `检测到 ${name}，推荐 GPU 版`,
  env_torch_cpu_note:  '未检测到 NVIDIA 显卡，只可安装 CPU 版',
  install_label:       (pkg, variant) => `正在安装 ${pkg}${variant === 'torch_gpu' ? '（GPU 版）' : variant === 'torch_cpu' ? '（CPU 版）' : ''}…`,
  install_ing:         (label) => `安装中：${label}`,
  install_done:        '✓ 安装完成',
  install_fail:        '✗ 安装失败',
  install_fail_hint:   '请检查网络或手动运行 pip install',

  /* ── 模型状态标签 ── */
  model_downloaded:    '已下载',
  model_not_downloaded:'未下载',
  model_detected:      '已检测到',
  model_not_detected:  '未检测到',
  model_not_detected_dl:'未检测，首次将下载',
  python_set:          '已设置',
  python_auto:         '将自动检测',
  whisper_dir_label:   'Whisper 模型目录',
  whisper_dir_label_dl:'Whisper 模型存储目录（下载位置）',
  demucs_dir_label:    'Demucs 模型目录',
  demucs_dir_label_dl: 'Demucs 模型存储目录（下载位置）',

  /* ── 模型下拉选项 ── */
  whisper_model_turbo: 'large-v3-turbo（推荐 · 快且质量高）',
  whisper_model_v3:    'large-v3（最高质量 · 慢 · 显存高）',
  whisper_model_v2:    'large-v2（老牌稳定）',
  whisper_model_distil:'distil-large-v3（蒸馏 · 接近 large 质量 · 更快）',
  whisper_model_medium:'medium（中等质量 · CPU 可用）',
  whisper_model_small: 'small（轻量 · CPU 友好）',
  whisper_model_base:  'base（极轻 · CPU 友好）',
  whisper_model_tiny:  'tiny（最轻最快 · 精度低 · CPU 首选）',
  demucs_model_ht:     'htdemucs（默认 · 推荐）',
  demucs_model_ht_ft:  'htdemucs_ft（更好 · 慢约 4 倍）',
  demucs_model_ht_6s:  'htdemucs_6s（分离 6 个声部 · 慢）',
  demucs_model_mdx:    'mdx_extra（MDX 架构 · 备选）',
  demucs_model_mdx_q:  'mdx_extra_q（量化版 · CPU 友好）',
  demucs_model_mdx_q2: 'mdx_q（量化版 · CPU 友好）',

  /* ── 任务卡片 / 状态 ── */
  status_running:      '处理中',
  status_retrying:     '等待重试',
  status_queued:       '排队中',
  status_done:         '已完成',
  status_error:        '失败',
  status_canceled:     '已取消',
  tag_music:           '含音乐',
  card_detail_title:   '查看详情',
  btn_cancel_task:     '✕ 取消',
  btn_open_folder:     '📂 打开',
  btn_remove:          '移除',
  step_done:           '完成',
  step_queued:         '排队等待中…',
  step_processing:     (n, total, step) => `第${n}/${total}步 · ${step}`,
  step_eta:            (min) => ` · 预计 ${min} 分`,
  step_elapsed:        (t) => `用时 ${t}`,
  step_indeterminate:  '处理中…',
  pct_done:            '100%',
  music_hint_yes:      '首次需联网下载分离模型（约数百 MB）',
  music_note_yes:      '首次使用需联网下载人声分离模型（约数百 MB），过程中无进度显示，请耐心等待。',
  outdir_default:      '默认目录',
  music_has:           '有背景音乐，需分离（点击取消）',
  music_none:          '无背景音乐（点击标记需分离）',
  btn_set_outdir:      '设置此文件的输出位置',
  confirm_outdir_default: '默认目录',
  fmt_no_unify_auto:   '不统一',

  /* ── 任务详情弹窗 ── */
  detail_title:        '任务详情',
  detail_step:         '当前步骤',
  detail_processed:    '转写进度',
  detail_duration:     '文件时长',
  detail_eta:          '预计耗时',
  detail_elapsed:      '已用时',
  detail_fmt:          '导出格式',
  detail_music:        '含背景音乐',
  detail_outdir:       '输出目录',
  btn_open_folder2:    '📂 打开文件夹',
  btn_close:           '关闭',
  detail_duration_val: (min) => `${min} 分钟`,
  detail_eta_val:      (min) => `约 ${min} 分钟`,
  detail_music_yes:    '是（含人声分离）',
  detail_music_no:     '否',
  detail_done:         '已完成',
  detail_step_of:      (n, total, step) => `第 ${n} 步 / 共 ${total} 步 · ${step}`,

  /* ── 删除弹窗 ── */
  remove_title:        '删除任务',
  remove_hint:         '这是一个已成功转写的任务，你想怎么删除？',
  btn_remove_record:   '仅删除任务记录（保留文档）',
  btn_remove_with_file:'删除记录并删除生成的文档',

  /* ── 下载进度 ── */
  downloading:         '下载中…',
  downloaded:          '✓ 已下载',
  download_fail:       (msg) => `模型下载失败${msg ? '：' + msg : '（查看控制台日志）'}`,

  /* ── main.js 警告 / 错误（发送到 renderer 显示） ── */
  warn_no_python:      '未找到 Python（请在设置里指定 python.exe，并确保已 pip install faster-whisper demucs）',
  warn_no_pipeline:    (p) => `找不到后端脚本 pipeline.py：${p}`,
  warn_no_fw:          'Python 环境未安装 faster-whisper，请运行：pip install faster-whisper',
  warn_no_demucs:      'Python 环境未安装 demucs（"有背景音乐"功能不可用），可运行：pip install demucs',
  warn_no_ffmpeg:      '未找到 ffmpeg/ffprobe（请安装 ffmpeg 并加入 PATH，或在设置里指定目录）',
  warn_cpu_mode:       '当前以 CPU 模式运行（未检测到 CUDA GPU），转写和人声分离速度均较慢。建议在设置里切换为更小的模型以提升速度。',
  step_no_fw:          '缺少依赖：请运行 pip install faster-whisper',
  step_no_demucs:      '缺少依赖：请运行 pip install demucs',
  step_preparing:      '准备中...',
  step_separating:     '正在分离人声',
  step_loading_model:  '加载模型中',
  step_transcribing:   '正在转写',
  step_oom_retry:      '显存不足，等待后重试...',
  step_oom_fail:       '失败：显存不足',
  step_fail:           (code) => `失败（退出码 ${code}）`,
  step_start_fail:     (msg) => `启动失败：${msg}`,
  step_canceled:       '已取消',
  step_complete:       '完成',
  env_install_no_python: '未找到 Python，请先在设置里指定 Python 路径',
  env_install_fail:    (label, code) => `安装 ${label} 失败（退出码 ${code}）`,

  /* ── 日志面板 ── */
  logsTitle:           '应用日志',
  logsDate:            '日期',
  logsCopy:            '复制',
  copy:                '复制',
  copied:              '已复制',
  close:               '关闭',
  logsClear:           '清空此日',
  logsClearConfirm:    '确定清空该日志？',
  logsOpenFolder:      '打开日志文件夹',
  logsNoDate:          '（无日志）',
  logsEmpty:           '（暂无日志）',
  logsSelectAll:       '全选 / 全不选',
  logsCopySel:         '复制选中',
  logsHint:            '勾选要复制的错误段，点"复制"。不勾选则复制全部。',
  btn_uninstall:       '🗑 卸载软件',
  uninstallConfirm:    '确定要卸载 Audio2Text 吗？将关闭应用并启动卸载程序。',
};

/* 双上下文兼容 */
if (typeof window !== 'undefined') window.S = S;
if (typeof module !== 'undefined') module.exports = S;
